# 고객 Segmentation

고객 세그먼테이션(Customer Segmentation)은 다양한 기준으로 고객을 분류하는 기법이다.
고객 세그먼테이션은 CRM이나 마케팅의 중요 기법 요소중 하나이다.

고객의 다음 속성을 기반으로 세그먼테이션을 수행한다.
- 사는 지역
- 결혼 여부
- 성별
- 소득
- 직업
- 선호 상품군
- 월별 사용액
- VIP 상품 사용 여부
- 최근 구매 상품
- 구매 주기
- 연간 프로모션 참가 횟수
- 고객 분석 요소인 RFM을 적용하여 고객 세그먼테이션 수행

RFM 기법은 Recency(R), Frequency(F), Monetary Value(M)의 각 앞글자를 합한 것으로 의미는 다음과 같다.

- RECENCY (R): 가장 최근 상품 구입 일에서 오늘까지의 기간
- FREQUENCY (F): 상품 구매 횟수
- MONETARY VALUE (M): 총 구매 금액

## UCI 온라인 판매
https://archive.ics.uci.edu/dataset/352/online+retail

| 변수명 | 유형 | 설명 |  |
| --- | --- | --- | --- |
| InvoiceNo | 범주형 | 각 거래에 고유하게 부여된 6자리 숫자. 'C'로 시작하면 거래 취소를 의미함. |  |
| StockCode | 범주형 | 각 제품에 고유하게 부여된 5자리 숫자 코드. |  |
| Description | 범주형 | 제품의 이름. |  |
| Quantity | 정수형 | 거래당 각 제품의 수량. |  |
| InvoiceDate | 날짜/시간형 | 거래가 발생한 날짜와 시간. |  |
| UnitPrice | 연속형 | 제품 단가 (영국 파운드화 기준). |  |
| CustomerID | 범주형 | 각 고객에게 고유하게 부여된 5자리 숫자. |  |
| Country | 범주형 | 고객이 거주하는 국가명. |  |

In [98]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [99]:
# %conda install openpyxl

In [100]:
# 데이터로드
retail_df = pd.read_excel('data/Online Retail.xlsx')
retail_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [101]:
retail_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [102]:
retail_df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  541909.000000                      541909  541909.000000  406829.000000
mean        9.552250  2011-07-04 13:34:57.156386       4.611114   15287.690570
min    -80995.000000         2010-12-01 08:26:00  -11062.060000   12346.000000
25%         1.000000         2011-03-28 11:34:00       1.250000   13953.000000
50%         3.000000         2011-07-19 17:17:00       2.080000   15152.000000
75%        10.000000         2011-10-19 11:27:00       4.130000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       218.081158                         NaN      96.759853    1713.600303

### 데이터 전처리
- 결측치 탐지/처리
- 이상치 탐지/처리
- 불필요한 컬럼 제거

### RFM 기반 데이터 가공
- Recency: 최근 구매일기준
- Frequency: 고객별 구매건수
- Monetary Value: 총구매가격 (단위가격 * 수량)

### RFM 고객 분류

### 군집화

### 클러스터별 페르소나 분석